Stability improved. Latency reduced. Also fixes #76.

diff --git a/bin/nvrun b/bin/nvrun
--- a/bin/nvrun
+++ b/bin/nvrun
@@ -2,30 +2,33 @@
 
 PATH=/usr/local/sbin:/usr/local/bin:$PATH
 
-TIMEOUT=20          # wait timeout for X server start
+TIMEOUT=4          # wait timeout for X server start
 let INTEL_IF_FAIL=1 # run on Intel if nVidia fails
 
 LOCK_FILE=/tmp/.snail.lock
 FIFO_FILE=/tmp/.snail.fifo
 
 {
-  echo -n > $FIFO_FILE &
-  flock -w $TIMEOUT -s 9
+  flock -w 0 -s 9
+  if [ 0 -ne $? ]; then
+    (nohup echo -n > $FIFO_FILE &>/dev/null)&
+    flock -w $TIMEOUT -s 9
+  fi
 
   if [ 0 -eq $? ]; then
-	echo "Running $@ on nVidia"
-	export LD_LIBRARY_PATH=/usr/lib/snail
-	LD_PRELOAD="/usr/lib/snail/lib32/libGL.so.1 \
-                    /usr/lib/snail/lib32/libnvidia-tls.so \
-                    /usr/lib/snail/lib32/libnvidia-core.so" \
-	snail.vglrun -d :8293 "$@" 2>/dev/null
-	echo "Application $@ was performed on nVidia"
+    echo "Running $@ on nVidia"
+    export LD_LIBRARY_PATH=/usr/lib/snail
+    LD_PRELOAD="/usr/lib/snail/lib32/libGL.so.1 \
+                /usr/lib/snail/lib32/libnvidia-tls.so \
+                /usr/lib/snail/lib32/libnvidia-core.so" \
+    snail.vglrun -d :8293 "$@" 2>/dev/null
+    echo "Application $@ was performed on nVidia"
 
   elif [ 0 -ne $INTEL_IF_FAIL ]; then
-  	echo "Failed to run $@ on nVidia ;-("
-	# echo "Running $@ on Intel"
-	# "$@"
-	# echo "Application $@ was performed on Intel"
+    echo "Failed to run $@ on nVidia ;-("
+    # echo "Running $@ on Intel"
+    # "$@"
+    # echo "Application $@ was performed on Intel"
   fi
 
   flock -u 9
